# Generated by Django 4.0.4 on 2022-06-22 02:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('budget_active', models.BooleanField(default=True)),
                ('number_in_party', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('vacation_start', models.DateField()),
                ('vacation_end', models.DateField()),
                ('amt_saved', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('last_update', models.DateField(auto_now=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='appreview',
            name='star_rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.CreateModel(
            name='VacationExpense',
            fields=[
                ('vacation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='budget.vacation')),
                ('flight', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('flight_per_person', models.BooleanField(default=False)),
                ('hotel', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('hotel_per_day', models.BooleanField(default=False)),
                ('food', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('food_pp_pd', models.BooleanField(default=False)),
                ('actvity', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('activity_pp_pd', models.BooleanField(default=False)),
            ],
            bases=('budget.vacation',),
        ),
    ]
