# Generated by Django 4.0.4 on 2022-07-08 01:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_vacation_alter_appreview_star_rating_vacationexpense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='amt_saved',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
